// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVIRV48Tgt-0h4SdF2B_zmJtWqq_OMmKM',
    appId: '1:827499930358:web:163866498f4e4a7243c2d7',
    messagingSenderId: '827499930358',
    projectId: 'flutter-rigelapplication-isw9a',
    authDomain: 'flutter-rigelapplication-isw9a.firebaseapp.com',
    databaseURL: 'https://flutter-rigelapplication-isw9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-rigelapplication-isw9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBayMCDwm-1XOyaQFiee4QBGLGDa_UpLd4',
    appId: '1:827499930358:android:1aa652e06c287ae243c2d7',
    messagingSenderId: '827499930358',
    projectId: 'flutter-rigelapplication-isw9a',
    databaseURL: 'https://flutter-rigelapplication-isw9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-rigelapplication-isw9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHYrTP1JwzsGq5_rVhCeJr8j7pmiGvQE',
    appId: '1:827499930358:ios:c7f4a4126a25a1f543c2d7',
    messagingSenderId: '827499930358',
    projectId: 'flutter-rigelapplication-isw9a',
    databaseURL: 'https://flutter-rigelapplication-isw9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-rigelapplication-isw9a.appspot.com',
    iosClientId: '827499930358-c2iktk5dv6v5r1i331o1eos0lqrd2ih3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rigelApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHYrTP1JwzsGq5_rVhCeJr8j7pmiGvQE',
    appId: '1:827499930358:ios:c7f4a4126a25a1f543c2d7',
    messagingSenderId: '827499930358',
    projectId: 'flutter-rigelapplication-isw9a',
    databaseURL: 'https://flutter-rigelapplication-isw9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-rigelapplication-isw9a.appspot.com',
    iosClientId: '827499930358-c2iktk5dv6v5r1i331o1eos0lqrd2ih3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rigelApplication',
  );
}
